In [1]:
"""ゼロから作るディープラーニング自然言語編のチャプター1"""

'ゼロから作るディープラーニング自然言語編のチャプター1'

In [2]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [13]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape
W.ndim

2

In [14]:
X = np.array([[0, 1, 2], [1, 2, 3]])

In [15]:
print(W, X)

[[1 2 3]
 [4 5 6]] [[0 1 2]
 [1 2 3]]


In [16]:
W + X

array([[1, 3, 5],
       [5, 7, 9]])

In [18]:
W * X

array([[ 0,  2,  6],
       [ 4, 10, 18]])

In [19]:
A = np.array([[1, 2,], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

In [20]:
b * A

array([[10, 40],
       [30, 80]])

In [21]:
b = np.array([[1], [2]])
A * b

array([[1, 2],
       [6, 8]])

In [22]:
A

array([[1, 2],
       [3, 4]])

In [23]:
b * A

array([[1, 2],
       [6, 8]])

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [28]:
b = np.array([[1, 2], [3, 4]])
np.dot(a, b)

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [29]:
print(a.shape)
print(b.shape)

(3,)
(2, 2)


In [30]:
b = np.array([[1], [2], [3]])
np.dot(a, b)

array([14])

In [31]:
print(a.shape)
print(b.shape)

(3,)
(3, 1)


In [32]:
a

array([1, 2, 3])

In [33]:
b

array([[1],
       [2],
       [3]])

In [34]:
a.ndim

1

In [35]:
b.ndim

2

In [36]:
W1 = np.random.randn(2, 4)
W1

array([[-0.70500119, -0.42538039,  0.90407437,  0.11561485],
       [ 1.11202698,  0.66149814,  1.10370689, -1.90693322]])

In [39]:
b1 = np.random.randn(4)
b1

array([-0.39235837, -0.18390902,  0.66484321,  1.22541774])

In [40]:
x = np.random.randn(10, 2)
x

array([[ 0.93874015, -0.44897019],
       [-2.34635352, -1.03482423],
       [-0.0995061 ,  0.04397998],
       [-1.53619989, -0.0900793 ],
       [ 1.4774822 , -1.37585396],
       [ 1.40379831,  1.08718467],
       [ 0.41254768, -0.60946337],
       [ 0.20067452, -1.17724578],
       [ 0.24075351,  0.36615717],
       [-0.51824063,  1.4642944 ]])

In [50]:
h = np.dot(x, W1) + b1

In [51]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [52]:
sigmoid(h[1])

array([0.52773929, 0.53236704, 0.06923003, 0.94918852])

In [53]:
h[1]

array([ 0.1110712 ,  0.12964946, -2.59857749,  2.92748513])

In [56]:
a = sigmoid(h)

In [58]:
print(h)
print(a)

[[-1.55343826 -0.88022362  1.01800263  2.19010621]
 [ 0.1110712   0.12964946 -2.59857749  2.92748513]
 [-0.27329953 -0.1124884   0.6234233   1.13004647]
 [ 0.59049377  0.409973   -0.82341687  1.21958543]
 [-2.9639718  -1.72252581  0.4820575   4.01989824]
 [-0.17305917 -0.06188666  3.13391449 -0.68547089]
 [-1.36094468 -0.7625576   0.36514808  2.43532032]
 [-1.8429632  -1.04801791 -0.45306637  3.49354777]
 [-0.15491323 -0.04410856  1.28663248  0.55501516]
 [ 1.60133676  1.00516839  1.81246696 -1.6268102 ]]
[[0.17459023 0.29313144 0.73458335 0.89935752]
 [0.52773929 0.53236704 0.06923003 0.94918852]
 [0.43209725 0.47190752 0.65099672 0.75584748]
 [0.64347843 0.60108141 0.30503883 0.77199058]
 [0.0490803  0.15154611 0.61823361 0.9823619 ]
 [0.45684287 0.48453327 0.95827021 0.33504135]
 [0.20408681 0.31809124 0.59028606 0.9194813 ]
 [0.13670122 0.2596059  0.38863196 0.97050363]
 [0.46134896 0.48897465 0.78357666 0.63529836]
 [0.83220513 0.73207353 0.85965976 0.1642678 ]]


In [59]:
W2 = np.random.randn(4, 3)
W2

array([[-0.41262334,  1.97008763, -0.63222509],
       [ 0.29535558,  0.57732964,  1.11192295],
       [ 0.35102712,  0.46954139,  0.20297257],
       [ 0.46288728, -0.9351496 , -0.74717734]])

In [60]:
b2 = np.random.randn(3)

In [63]:
h = np.dot(x, W1) + b1

In [64]:
a = sigmoid(h)

In [65]:
s = np.dot(a, W2) + b2

In [66]:
s

array([[-1.16715363,  1.14271674, -0.36157733],
       [-1.45270252,  1.61755876, -0.49111653],
       [-1.31637467,  1.84819683, -0.23533284],
       [-1.47941141,  2.16167444, -0.30762364],
       [-1.15960356,  0.68145725, -0.52529358],
       [-1.40978068,  2.44203139,  0.13984611],
       [-1.2132898 ,  1.12866532, -0.39679685],
       [-1.24992738,  0.81974602, -0.49827816],
       [-1.33266523,  2.09066185, -0.11786751],
       [-1.60521535,  3.43783741,  0.28536128]])

In [67]:
x = np.random.randn(3)
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [68]:
np.exp(x)

array([7.46833729, 0.46952821, 0.79772198])

In [69]:
math.e

NameError: name 'math' is not defined

In [70]:
import math

In [71]:
math.e

2.718281828459045

In [72]:
math.e ** x

array([7.46833729, 0.46952821, 0.79772198])

In [73]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [74]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [75]:
math.e ** -0.2

0.8187307530779818

In [91]:
np.exp(-0.18)

0.835270211411272

In [93]:
sum([1, 2, 3])

6

In [94]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [95]:
sum(np.exp(x))

8.735587476477724

In [99]:
np.exp(x[2])/sum(np.exp(x))

0.09131864172295115

In [100]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [101]:
np.exp(x)

array([7.46833729, 0.46952821, 0.79772198])

In [102]:
s = np.exp(x)

In [103]:
s

array([7.46833729, 0.46952821, 0.79772198])

In [104]:
sum(np.exp(s))

1755.5114192396275

In [105]:
sum(s)

8.735587476477724

In [106]:
y = s / sum(s)

In [107]:
y

array([0.85493246, 0.0537489 , 0.09131864])