In [1]:
import numpy as np
t = np.random.randn(10)
t

array([ 0.74439197,  0.92446048,  0.35653185, -0.34792084,  0.58073463,
        0.24703549,  0.11702003,  0.61007428, -1.01223971,  1.25329274])

In [2]:
np.tanh(t)

array([ 0.63179136,  0.72800072,  0.34215555, -0.33453035,  0.52319917,
        0.24212996,  0.11648879,  0.54417939, -0.7666868 ,  0.8492044 ])

In [3]:
xs = np.arange(80).reshape(2, 4, 10)

In [4]:
xs

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]])

In [8]:
N, T, D = xs.shape
print(N, T, D)

2 4 10


In [17]:
Wx = np.arange(60).reshape(10, 6)

In [23]:
D, H = Wh.shape

In [24]:
hs = np.empty((N, T, H), dtype='f')

In [21]:
np.dot(xs, Wx).shape

(2, 4, 6)

In [25]:
xs[:, 1, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [27]:
0.01 * np.random.uniform(10, 10)

0.1

In [36]:
t = 1
y = np.array([0.7])
y

array([0.7])

In [37]:
- (t * np.log(y))

array([0.35667494])