In [1]:
"""ゼロから作るディープラーニング自然言語編のチャプター1"""

'ゼロから作るディープラーニング自然言語編のチャプター1'

In [2]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [13]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape
W.ndim

2

In [14]:
X = np.array([[0, 1, 2], [1, 2, 3]])

In [15]:
print(W, X)

[[1 2 3]
 [4 5 6]] [[0 1 2]
 [1 2 3]]


In [16]:
W + X

array([[1, 3, 5],
       [5, 7, 9]])

In [18]:
W * X

array([[ 0,  2,  6],
       [ 4, 10, 18]])

In [19]:
A = np.array([[1, 2,], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

In [20]:
b * A

array([[10, 40],
       [30, 80]])

In [21]:
b = np.array([[1], [2]])
A * b

array([[1, 2],
       [6, 8]])

In [22]:
A

array([[1, 2],
       [3, 4]])

In [23]:
b * A

array([[1, 2],
       [6, 8]])

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [28]:
b = np.array([[1, 2], [3, 4]])
np.dot(a, b)

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [29]:
print(a.shape)
print(b.shape)

(3,)
(2, 2)


In [30]:
b = np.array([[1], [2], [3]])
np.dot(a, b)

array([14])

In [31]:
print(a.shape)
print(b.shape)

(3,)
(3, 1)


In [32]:
a

array([1, 2, 3])

In [33]:
b

array([[1],
       [2],
       [3]])

In [34]:
a.ndim

1

In [35]:
b.ndim

2

In [36]:
W1 = np.random.randn(2, 4)
W1

array([[-0.70500119, -0.42538039,  0.90407437,  0.11561485],
       [ 1.11202698,  0.66149814,  1.10370689, -1.90693322]])

In [39]:
b1 = np.random.randn(4)
b1

array([-0.39235837, -0.18390902,  0.66484321,  1.22541774])

In [40]:
x = np.random.randn(10, 2)
x

array([[ 0.93874015, -0.44897019],
       [-2.34635352, -1.03482423],
       [-0.0995061 ,  0.04397998],
       [-1.53619989, -0.0900793 ],
       [ 1.4774822 , -1.37585396],
       [ 1.40379831,  1.08718467],
       [ 0.41254768, -0.60946337],
       [ 0.20067452, -1.17724578],
       [ 0.24075351,  0.36615717],
       [-0.51824063,  1.4642944 ]])

In [50]:
h = np.dot(x, W1) + b1

In [51]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [52]:
sigmoid(h[1])

array([0.52773929, 0.53236704, 0.06923003, 0.94918852])

In [53]:
h[1]

array([ 0.1110712 ,  0.12964946, -2.59857749,  2.92748513])

In [56]:
a = sigmoid(h)

In [58]:
print(h)
print(a)

[[-1.55343826 -0.88022362  1.01800263  2.19010621]
 [ 0.1110712   0.12964946 -2.59857749  2.92748513]
 [-0.27329953 -0.1124884   0.6234233   1.13004647]
 [ 0.59049377  0.409973   -0.82341687  1.21958543]
 [-2.9639718  -1.72252581  0.4820575   4.01989824]
 [-0.17305917 -0.06188666  3.13391449 -0.68547089]
 [-1.36094468 -0.7625576   0.36514808  2.43532032]
 [-1.8429632  -1.04801791 -0.45306637  3.49354777]
 [-0.15491323 -0.04410856  1.28663248  0.55501516]
 [ 1.60133676  1.00516839  1.81246696 -1.6268102 ]]
[[0.17459023 0.29313144 0.73458335 0.89935752]
 [0.52773929 0.53236704 0.06923003 0.94918852]
 [0.43209725 0.47190752 0.65099672 0.75584748]
 [0.64347843 0.60108141 0.30503883 0.77199058]
 [0.0490803  0.15154611 0.61823361 0.9823619 ]
 [0.45684287 0.48453327 0.95827021 0.33504135]
 [0.20408681 0.31809124 0.59028606 0.9194813 ]
 [0.13670122 0.2596059  0.38863196 0.97050363]
 [0.46134896 0.48897465 0.78357666 0.63529836]
 [0.83220513 0.73207353 0.85965976 0.1642678 ]]


In [59]:
W2 = np.random.randn(4, 3)
W2

array([[-0.41262334,  1.97008763, -0.63222509],
       [ 0.29535558,  0.57732964,  1.11192295],
       [ 0.35102712,  0.46954139,  0.20297257],
       [ 0.46288728, -0.9351496 , -0.74717734]])

In [60]:
b2 = np.random.randn(3)

In [63]:
h = np.dot(x, W1) + b1

In [64]:
a = sigmoid(h)

In [65]:
s = np.dot(a, W2) + b2

In [66]:
s

array([[-1.16715363,  1.14271674, -0.36157733],
       [-1.45270252,  1.61755876, -0.49111653],
       [-1.31637467,  1.84819683, -0.23533284],
       [-1.47941141,  2.16167444, -0.30762364],
       [-1.15960356,  0.68145725, -0.52529358],
       [-1.40978068,  2.44203139,  0.13984611],
       [-1.2132898 ,  1.12866532, -0.39679685],
       [-1.24992738,  0.81974602, -0.49827816],
       [-1.33266523,  2.09066185, -0.11786751],
       [-1.60521535,  3.43783741,  0.28536128]])

In [67]:
x = np.random.randn(3)
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [68]:
np.exp(x)

array([7.46833729, 0.46952821, 0.79772198])

In [69]:
math.e

NameError: name 'math' is not defined

In [70]:
import math

In [71]:
math.e

2.718281828459045

In [72]:
math.e ** x

array([7.46833729, 0.46952821, 0.79772198])

In [73]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [74]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [75]:
math.e ** -0.2

0.8187307530779818

In [91]:
np.exp(-0.18)

0.835270211411272

In [93]:
sum([1, 2, 3])

6

In [94]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [95]:
sum(np.exp(x))

8.735587476477724

In [99]:
np.exp(x[2])/sum(np.exp(x))

0.09131864172295115

In [100]:
x

array([ 2.01067239, -0.75602691, -0.22599513])

In [101]:
np.exp(x)

array([7.46833729, 0.46952821, 0.79772198])

In [102]:
s = np.exp(x)

In [103]:
s

array([7.46833729, 0.46952821, 0.79772198])

In [104]:
sum(np.exp(s))

1755.5114192396275

In [105]:
sum(s)

8.735587476477724

In [106]:
y = s / sum(s)

In [107]:
y

array([0.85493246, 0.0537489 , 0.09131864])

In [109]:
x = np.array([2.41838292, 1.25261084, 2.14780091])
x

array([2.41838292, 1.25261084, 2.14780091])

In [110]:
y = x / sum(x)

In [111]:
y

array([0.41561579, 0.21526981, 0.3691144 ])

In [112]:
x

array([2.41838292, 1.25261084, 2.14780091])

In [113]:
t = [1, 0, 0]

In [114]:
range(1)

range(0, 1)

In [115]:
a = range(3)

In [116]:
a

range(0, 3)

In [117]:
for i in a:
    print(i)

0
1
2


In [118]:
x.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [119]:
x.size

3

In [121]:
for a in x:
    print(a)

2.41838292
1.25261084
2.14780091


In [122]:
print(t)
print(x)

[1, 0, 0]
[2.41838292 1.25261084 2.14780091]


In [123]:
ts = t
ts

[1, 0, 0]

In [124]:
xs = x

In [125]:
sx

[]

In [126]:
xs

array([2.41838292, 1.25261084, 2.14780091])

In [133]:
ts = [0, 1, 0]
for (t, x) in zip(ts, xs):
    print(t * np.log(x))

0.0
0.22523004507141045
0.0


In [131]:
ts

[1, 0, 0]

In [137]:
xs

array([2.41838292, 1.25261084, 2.14780091])

In [138]:
xs[1]

1.25261084

In [139]:
np.log(xs[1])

0.22523004507141045

In [140]:
np.log(xs)

array([0.8830991 , 0.22523005, 0.76444449])

In [151]:
a = np.random.randint(0, 10, size=(2,5))
a

array([[9, 3, 2, 7, 4],
       [2, 6, 3, 0, 9]])

In [152]:
np.sum(a)

45

In [158]:
np.sum(a, axis=0).shape

(5,)

In [154]:
np.sum(a, axis=1)

array([25, 20])

In [157]:
np.sum(a, axis=0, keepdims=True).shape

(1, 5)

In [159]:
np.sum(a, axis=1, keepdims=True)

array([[25],
       [20]])

In [160]:
a.ndim

2

In [161]:
a

array([[9, 3, 2, 7, 4],
       [2, 6, 3, 0, 9]])

In [162]:
a.max

<function ndarray.max>

In [163]:
a - a.max

TypeError: unsupported operand type(s) for -: 'int' and 'builtin_function_or_method'

In [164]:
a.ndim

2

In [165]:
a - a.max(axis=1)

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [171]:
a2 = a - a.max(axis=1, keepdims=True)
a3 = np.exp(a2)
a4 = a3 / np.sum(a3, axis=1, keepdims=True)
print(a4[0])

[8.73008771e-01 2.16397239e-03 7.96080954e-04 1.18148889e-01
 5.88228683e-03]


In [177]:
b = np.random.randint(0, 10, size=(1, 5))

In [178]:
b

array([[0, 7, 0, 4, 4]])

In [179]:
np.exp(b) / np.sum(np.exp(b))

array([[8.27931454e-04, 9.07937086e-01, 8.27931454e-04, 4.52035258e-02,
        4.52035258e-02]])

In [180]:
np.max(b)

7

In [181]:
b = b - np.max(b)
b

array([[-7,  0, -7, -3, -3]])

In [182]:
b = np.exp(b) / np.sum(np.exp(b))
b

array([[8.27931454e-04, 9.07937086e-01, 8.27931454e-04, 4.52035258e-02,
        4.52035258e-02]])

In [183]:
t = np.array([[1, 2, 3]])

In [184]:
t

array([[1, 2, 3]])

In [185]:
t.ndim

2

In [186]:
t.reshape(1, t.size)

array([[1, 2, 3]])

In [188]:
print(t.reshape(1, t.size).ndim)

2


In [189]:
t

array([[1, 2, 3]])

In [190]:
t.ndim

2

In [191]:
t.shape

(1, 3)

In [192]:
t.ndim

2

In [193]:
t = np.array([1, 2, 3])

In [194]:
t.ndim

1

In [195]:
t.shape

(3,)

In [196]:
t = t.reshape(1, t.size)

In [197]:
t

array([[1, 2, 3]])

In [198]:
t.ndim

2

In [199]:
t.shape

(1, 3)

In [200]:
np.log(0.5)

-0.6931471805599453

In [201]:
math.log

<function math.log>

In [202]:
math.log(0.5)

-0.6931471805599453

In [203]:
np.log(0.2)

-1.6094379124341003

In [204]:
le-7

NameError: name 'le' is not defined

In [205]:
1e

SyntaxError: invalid syntax (<ipython-input-205-042564b69090>, line 1)

In [206]:
1math.e

SyntaxError: invalid syntax (<ipython-input-206-45f1ced93749>, line 1)

In [207]:
math.e

2.718281828459045

In [209]:
1e-5

1e-05

In [210]:
print(1e-4)

0.0001


In [234]:
delta = 1e-7

In [235]:
np.log(0.5+delta)

-0.6931469805599654

In [236]:
a = np.array([0.7, 0.2, 0.1])
t = np.array([1, 0, 0])
delta = 1e-7

In [237]:
-np.sum(t*np.log(a+delta))

0.3566748010815999

In [238]:
def cross_entropy_error(y, t):
    return -np.sum(t*np.log(y+1e-7))

In [239]:
cross_entropy_error(a, t)

0.3566748010815999

In [240]:
a

array([0.7, 0.2, 0.1])

In [241]:
x

2.14780091

In [242]:
x = xs

In [243]:
x

array([2.41838292, 1.25261084, 2.14780091])

In [245]:
np.maximum(0, x)

array([2.41838292, 1.25261084, 2.14780091])

In [248]:
m = np.maximum(0, a)

In [249]:
m

array([0.7, 0.2, 0.1])

In [250]:
a = np.array([-0.1, -0.4, -0.9])
a

array([-0.1, -0.4, -0.9])

In [251]:
np.maximum(0, a)

array([0., 0., 0.])

In [252]:
one_dim = np.arange(5)

In [253]:
one_dim.ndim

1

In [254]:
y

array([0.41561579, 0.21526981, 0.3691144 ])

In [255]:
y.ndim

1

In [256]:
y

array([0.41561579, 0.21526981, 0.3691144 ])

In [257]:
a

array([-0.1, -0.4, -0.9])

In [260]:
a.argmax(axis=0)

0

In [261]:
a = np.array([4, 1, 9])

In [262]:
a.argmax()

2

In [263]:
a

array([4, 1, 9])

In [264]:
a[1, 2]

IndexError: too many indices for array

In [265]:
a.shape

(3,)

In [266]:
a = np.random.randint(4, 10, size=(3, 4))

In [267]:
a

array([[5, 6, 9, 8],
       [6, 6, 7, 5],
       [7, 8, 9, 9]])

In [270]:
a[np.arange(1), 2]

array([9])

In [272]:
np.arange(3)

array([0, 1, 2])

In [277]:
a[np.arange(2), 1]

array([6, 6])

In [278]:
t = np.array([[0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1]])

In [279]:
t

array([[0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1]])

In [280]:
t2 = t.argmax()

In [281]:
t2

1

In [282]:
t2 = t.argmax(axis=1)

In [283]:
t2

array([1, 1, 1, 0, 0, 1, 0, 1])

In [284]:
t2[3]

0

In [285]:
t2[4, 1]

IndexError: too many indices for array

In [286]:
a

array([[5, 6, 9, 8],
       [6, 6, 7, 5],
       [7, 8, 9, 9]])

In [287]:
a[4, 2]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [289]:
a[np.arange(3), 2]

array([9, 7, 9])

In [290]:
a

array([[5, 6, 9, 8],
       [6, 6, 7, 5],
       [7, 8, 9, 9]])

In [291]:
a[np.arange(2), 2]

array([9, 7])

In [292]:
a.shape

(3, 4)

In [293]:
a.shape[-]

SyntaxError: invalid syntax (<ipython-input-293-ecbee16d398d>, line 1)

In [294]:
a.shape[0]

3

In [299]:
a[np.arange(a.shape[0]), [[1], [1], [1], [1]]]

array([[6, 6, 8],
       [6, 6, 8],
       [6, 6, 8],
       [6, 6, 8]])

In [300]:
t = np.array([[0, 1], [0, 1], [0, 1], [1, 0], [1, 0], [0, 1], [1, 0], [0, 1]])

In [301]:
a

array([[5, 6, 9, 8],
       [6, 6, 7, 5],
       [7, 8, 9, 9]])

In [303]:
a[np.arange(a.shape[0], t)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [304]:
a.ndim

2

In [305]:
t.size == a.size

True

In [306]:
t2 = t.argmax(axis=1)

In [307]:
t2

array([1, 0, 3])

In [308]:
a[np.arange(a.shape[0], t2)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [309]:
a

array([[5, 6, 9, 8],
       [6, 6, 7, 5],
       [7, 8, 9, 9]])

In [310]:
a[np.arange(a.shape[0], 1)]

array([], shape=(0, 4), dtype=int64)

In [311]:
a[np.arange(a.shape[0]), t2]

array([6, 6, 9])

In [312]:
batch_size = a.shape[0]

In [315]:
-np.sum(np.log(a[np.arange(batch_size), t2] + 1e-7)) / batch_size

-1.9269145200789246

In [316]:
t2

array([1, 0, 3])

In [329]:
a = np.random.rand(3, 4)
print(a)

[[0.9387432  0.89884343 0.97479544 0.04790255]
 [0.41399146 0.63564651 0.33562105 0.62675047]
 [0.49770257 0.07920848 0.66713487 0.95757753]]


In [331]:
t = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])

In [332]:
def cross_entropy_error(y, t):
    if t.size == y.size:
        t = t.argmax(axis=1)
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [333]:
cross_entropy_error(a, t)

0.1739961782114086

In [336]:
if t.size == a.size:
    t = t.argmax(axis=1)
np.log(a[np.arange(a.shape[0]), t])

array([-0.02552763, -0.45311268, -0.04334859])

In [337]:
t

array([2, 1, 3])

In [338]:
a

array([[0.9387432 , 0.89884343, 0.97479544, 0.04790255],
       [0.41399146, 0.63564651, 0.33562105, 0.62675047],
       [0.49770257, 0.07920848, 0.66713487, 0.95757753]])

In [340]:
a[np.arange(3), t]

array([0.97479544, 0.63564651, 0.95757753])

In [348]:
(np.log(0.07) + np.log(0.03) + np.log(0.05)) / 3

-3.0538500692689166

In [349]:
np.log(0.1)

-2.3025850929940455

In [350]:
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)

In [351]:
y

array([[ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321],
       [ 0.63291974,  1.33290981,  0.0626954 , -1.05121446, -0.1778295 ,
         0.23076189, -1.31546376, -0.22511321]])

In [355]:
np.random.randn(2, 3, 5)

array([[[ 0.22995647,  0.35508872,  0.58406909,  0.70829576,
          0.94754057],
        [-0.79801549, -0.8941236 ,  0.92920117,  2.04524318,
         -0.25619322],
        [-0.24011072,  0.29411031,  0.04362671,  1.12359632,
          0.74749079]],

       [[-0.71381053, -0.04718369, -0.47917518,  0.18349902,
          1.13276203],
        [-0.3075713 , -1.01761031, -0.61495632, -2.35379615,
          0.04825805],
        [-0.65236769,  1.27513221,  0.93094243,  0.37130894,
         -1.05013644]]])

In [358]:
np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [359]:
grads = [np.zeros_like(a), np.zeros_like(np.arange(4))]

In [360]:
grads

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([0, 0, 0, 0])]

In [361]:
grads

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([0, 0, 0, 0])]

In [364]:
grads[0][...] = 1

In [365]:
grads[0]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])